# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target '至美直播' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

# Pods for 至美直播
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'BarrageRenderer', '~> 1.8.0'
pod 'GPUImage'    # 由于LFLiveKit里面已经集成了GPUImage
#pod 'LFLiveKit', '~> 1.6'//
pod 'SDWebImage'
pod 'XXNibBridge'
pod 'UMengAnalytics'
pod 'IQKeyboardManager','3.3.7'
pod 'RongCloudIMLib'
pod 'BlocksKit'
#pod 'PLCameraStreamingKit'
pod 'PLMediaStreamingKit'
#pod 'LSStatusBarHUD' , :podspec=>'/Users/liusong/Desktop/github/LSStatusBarHUD/LSStatusBarHUD.podspec'
pod 'LSStatusBarHUD'

pod 'MSWeakTimer'

pod 'Qiniu'


# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMengUShare/UI'

# 集成新浪微博
pod 'UMengUShare/Social/Sina'

# 集成微信
pod 'UMengUShare/Social/WeChat'

# 集成QQ
pod 'UMengUShare/Social/QQ'

# 集成短信
pod 'UMengUShare/Social/SMS'



  target '至美直播Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '至美直播UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
